### ISSUE TITLE
Upload the current directory

### ISSUE THREAD

**Issue by simmstein** [clowzed/sero#23]
Hi, 

I have an error when I want to upload the current directory:

```
$ ls sero.toml
sero.toml
$ sero upload # or "sero upload ."
/usr/lib/node_modules/@clowzed/sero/node_modules/zip-a-folder/dist/lib/cjs/ZipAFolder.js:80
                    throw new Error('Source and target folder must be different.');
                          ^

Error: Source and target folder must be different.
    at ZipAFolder.<anonymous> (/usr/lib/node_modules/@clowzed/sero/node_modules/zip-a-folder/dist/lib/cjs/ZipAFolder.js:80:27)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@clowzed/sero/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/@clowzed/sero/node_modules/tslib/tslib.js:165:16)
    at ZipAFolder.compress (/usr/lib/node_modules/@clowzed/sero/node_modules/zip-a-folder/dist/lib/cjs/ZipAFolder.js:74:24)
    at /usr/lib/node_modules/@clowzed/sero/node_modules/zip-a-folder/dist/lib/cjs/ZipAFolder.js:59:34
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@clowzed/sero/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)

Node.js v21.6.1
```

**Comment by clowzed** [comment]
Thanks, @simmstein 
That's strange that there was no such problem before. I also faced this today and added that to todo list

Temporary workaround:

```
cd ..
sero upload ./<folder>
```

**Comment by clowzed** [comment]
@simmstein 
Hi also here) Same, the tool will be rewritten soon.
